spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books?serverTimezone=GMT%2b8 # 北京时间
    username: root
    password: root
server:
  port: 18103
mybatis:
  mapper-locations: classpath:mapper/*.xml
